
const VALID_BARANGAYS = [
  "ANIBAN I", "ANIBAN II", "BAYANAN", "DULONG BAYAN",
  "HABAY I", "HABAY II", "KAINGIN (POB.)",
  "KAINGIN DIGMAN",
  "LIGAS I", "LIGAS II",
  "MABOLO", "MALIKSI I", "MALIKSI II",
  "MAMBOG I", "MAMBOG II", "MAMBOG III", "MAMBOG IV",
  "MOLINO I", "MOLINO II", "MOLINO III", "MOLINO IV",
  "MOLINO V", "MOLINO VI", "MOLINO VII",
  "NIOG",
  "P.F. ESPIRITU I (PANAPAAN)", "P.F. ESPIRITU II",
  "P.F. ESPIRITU III", "P.F. ESPIRITU IV",
  "P.F. ESPIRITU V", "P.F. ESPIRITU VI",
  "QUEENS ROW CENTRAL", "QUEENS ROW EAST", "QUEENS ROW WEST",
  "REAL",
  "SALINAS I", "SALINAS II",
  "SAN NICOLAS I", "SAN NICOLAS II", "SAN NICOLAS III",
  "SINEGUELASAN",
  "TALABA I", "TALABA II", "TALABA III",
  "ZAPOTE I", "ZAPOTE II", "ZAPOTE III",
];

module.exports = { VALID_BARANGAYS };